Symfony/src/Lotofootv2/Bundle/Entity/LeagueDay.php
<?php

namespace Lotofootv2\Bundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * LeagueDay
 *
 * @ORM\Table(name="lfv2_league_day")
 * @ORM\Entity
 */
class LeagueDay
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="number", type="integer")
     */
    private $number;

    /**
     * @var integer
     *
     * @ORM\Column(name="league_id", type="integer")
     */
    private $league_id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deadline", type="datetime")
     */
    private $deadline;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="corrected", type="boolean")
     */
    private $corrected;

    /**
     * @var boolean
     *
     * @ORM\Column(name="word", type="string", length=1024, nullable=true)
     */
    private $word;
    /**
     * @var boolean
     *
     * @ORM\Column(name="king_tag", type="string", length=255, nullable=true)
     */
    private $king_tag;

    /**
     * Get id
     *
     * @return integer 
     */

    public function getId()
    {
        return $this->id;
    }

    /**
     * Set number
     *
     * @param integer $number
     * @return Day
     */
    public function setNumber($number)
    {
        $this->number = $number;
    
        return $this;
    }

    /**
     * Get number
     *
     * @return integer 
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set league_id
     *
     * @param integer $leagueId
     */
    public function setLeagueId($leagueId)
    {
        $this->league_id = $leagueId;
    
        return $this;
    }

    /**
     * Get league_id
     *
     * @return integer 
     */
    public function getLeagueId()
    {
        return $this->league_id;
    }

    /**
     * Set deadline
     *
     * @param \DateTime $deadline
     */
    public function setDeadline($deadline)
    {
        $this->deadline = $deadline;
    
        return $this;
    }

    /**
     * Get deadline
     *
     * @return \DateTime 
     */
    public function getDeadline()
    {
        return $this->deadline;
    }
    
    /**     
     */
    public function setCorrected($corrected)
    {
    	$this->corrected = $corrected;
    
    	return $this;
    }
    
    /**
     * Get deadline
     *
     * @return \DateTime
     */
    public function getCorrected()
    {
    	return $this->corrected;
    }
    
	/**     
     */
    public function setWord($word)
    {
    	$this->word = $word;
    
    	return $this;
    }
    
    /**
     * Get deadline
     *
     * @return String
     */
    public function getWord()
    {
    	return $this->word;
    }
    /**
     */
    public function setKingTag($king_tag)
    {
    $this->king_tag = $king_tag;
    
    return $this;
    }
    
    /**
    * Get deadline
    *
    * @return String
     */
    public function getKingTag()
    {
    return $this->king_tag;
    }
}

Symfony/src/Lotofootv2/Bundle/Controller/Admin/LeagueController.php
<?php

namespace Lotofootv2\Bundle\Controller\Admin;

use Lotofootv2\Bundle\Service\LeagueService;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\HttpFoundation\Request;
use Lotofootv2\Bundle\Entity\League;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class LeagueController extends Controller
{
	/**
     * @Route("/admin/league", name="_admin_league")
     */
    public function indexAction()
    {
    	$ls = $this->get('league_service');
    	$league = $ls->getRunningLeague();
		
		$this->get('logger')->info('This will be written in logs'.$league);
		
		$toCorrect = $this->get('league_service')->getNotCorrectedLeagueDay() != null;
		
		return $this->render('Lotofootv2Bundle:Admin:league.html.twig', 
			array('league' => $league, 'toCorrect' => $toCorrect)
		);    	
    }
    
    /**
     * @Route("/admin/league/create", name="_admin_league_create")
     */
    public function createAction(Request $request)
    {
    	$league = new League();
    	$league->setName($request->request->get('name'));
    	$league->setOpened(true);
    	
    	$this->get('league_service')->createLeague($league);

    	return $this->redirect($this->generateUrl('_admin_league'));
    }
}

Symfony/src/Lotofootv2/Bundle/Controller/Admin/UsersController.php
<?php

namespace Lotofootv2\Bundle\Controller\Admin;

use Lotofootv2\Bundle\Service\LeagueService;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\HttpFoundation\Request;
use Lotofootv2\Bundle\Entity\News;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use \DateTime;

class UsersController extends Controller
{
	/**
     * @Route("/admin/users", name="_admin_users")
     */
    public function indexAction()
    {
    	$accounts = $this->get('account_service')->all();
    	
		return $this->render('Lotofootv2Bundle:Admin:users.html.twig', array('users'=>$accounts));    	
    }
    
	/**
     * @Route("/admin/users/activation", name="_admin_users_activation")
     */
    public function activationAction(Request $request)
    {
    	$id = $request->query->get('id');
    	
    	$acc = $this->get('account_service')->switchActivation($id);
    	
    	if($acc->isEnabled()){
    		$this->mailActivation($acc);
    	}else{
    		$this->mailDesactivation($acc);
    	}
		return $this->redirect($this->generateUrl('_admin_users'));
    }
    
    /**
     * @Route("/admin/users/activation_cagnoute", name="_admin_cagnoute_activation")
     */
    public function activationCagnoute(Request $request)
    {
    	$id = $request->query->get('id');
    	 
    	$acc = $this->get('account_service')->addCagnoute($id);
    	$acc = $this->get('reward_service')->rewardCupCagnoute($id);
    	return $this->redirect($this->generateUrl('_admin_users'));
    }
    
	private function mailActivation($account)
    {
    	$from = $this->container->getParameter('mailer_from');
    
    	$message = \Swift_Message::newInstance()
	        ->setSubject('[Lotofoot] Activation du compte')
	        ->setFrom($from)
	        ->setTo($account->getEmail())
	        ->setBody($this->renderView('Lotofootv2Bundle:mails:activation.txt.twig', 
	        	array('account' => $account)));
    	
	    $this->get('mailer')->send($message);
    }
    
	private function mailDesactivation($account)
    {
    	$from = $this->container->getParameter('mailer_from');
    
    	$message = \Swift_Message::newInstance()
	        ->setSubject('[Lotofoot] Désactivation du compte')
	        ->setFrom($from)
	        ->setTo($account->getEmail())
	        ->setBody($this->renderView('Lotofootv2Bundle:mails:deactivation.txt.twig', 
	        	array('account' => $account)));
    	
	    $this->get('mailer')->send($message);
    }

}

Symfony/src/Lotofootv2/Bundle/Controller/User/CL/BoardController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\CL;

use Symfony\Component\HttpFoundation\Request;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

use \Datetime;

class BoardController extends Controller
{
	/**
     * @Route("/cl/board", name="_cl_board")
     */
    public function indexAction(Request $request)
    {
        $tour =  $this->get('tournament_service')->getRunningTour();
        
        $data = array();
        
        if($tour != null){
        	$players = $this->get('tournament_service')->getTourPlayers($tour->getId());
        	
        	$accs = $this->get('account_service')->all();
        	
        	foreach($accs as $a){
        		//acc_accountid
        		$request->request->set('acc_'.$a->getId(), $a->getUsername());
        	}
        	
        	foreach($players as $p){
        		//step display
        		//step_stepid_groupnumber_groupposition
        		$base_key = 'step_'.$p->getTourStepNumber().'_'.$p->getGroupNumber().'_'.$p->getGroupPosition();
        		
        		$request->request->set($base_key.'_a', $p->getAccountId());
        		$request->request->set($base_key.'_pa', $p->getPointsA());
        		$request->request->set($base_key.'_pr', $p->getPointsR());
        		$request->request->set($base_key.'_pt', $p->getTotalPoints());
        	}
        }
    	
        return $this->render('Lotofootv2Bundle:User/CL:board.html.twig');
    }
    
    /**
     * @Route("/cl/board/results", name="_cl_board_results")
     */
    public function resultsAction(Request $request)
    {
    	
    	$tour_s = $this->get('tournament_service');
    	
        $tour_number = $request->query->get('tour_number');
        $group_number = $request->query->get('group_number');
    	
        $tour_steps = $tour_s->getTourStepsByNumber($tour_number);
        
        if($tour_steps == null || count($tour_steps) == 0){
        	return new Response("Aucune donnée");
        }
        
        $players = null;
        
        if(count($tour_steps) == 1){
        	$players = $tour_s->getTourStepPlayersByGroup($tour_steps[0]->getId(), $group_number);
        }else{//on a passé les players sur l'id du step n°2 (step retour)
        	$players = $tour_s->getTourStepPlayersByGroup($tour_steps[1]->getId(), $group_number);
        }
        
        $request->request->set('_acc_1', 'acc_'.$players[0]->getAccountId());
        $request->request->set('_acc_2', 'acc_'.$players[1]->getAccountId());
        
         $accs = $this->get('account_service')->all();
            
         foreach($accs as $a){
                //acc_accountid
             $request->request->set('acc_'.$a->getId(), $a->getUsername());
         }
        
        $data = array();
        
        for($i=0;$i<count($tour_steps);$i++){
        	$ts = $tour_steps[$i];

        	$matches = $tour_s->getTourStepMatches($ts->getId());
        	
        	if($ts->getState() == "A"){
        		$data['matchesA'] = $matches;
        	}else{
        		$data['matchesR'] = $matches;
        	}
        	
        	if($ts->getDeadline() < new DateTime()){
        		
        		for($p=0;$p<count($players);$p++){
        		    $votes = $tour_s->getTourStepVotes($ts->getId(), $players[$p]->getAccountId());
        		    
        		    for($v=0;$v<count($votes);$v++){
                        $vote = $votes[$v];
                        $request->request->set($vote->getTourMatchId().'_result_'.$players[$p]->getGroupPosition(), $vote->getResult());
                        $request->request->set($vote->getTourMatchId().'_score_'.$players[$p]->getGroupPosition(), $vote->getScore());
                        $request->request->set($vote->getTourMatchId().'_fgmin_'.$players[$p]->getGroupPosition(), $vote->getFirstGoalMin());
        		    }        		
        		}
        	}
        }
          
        return $this->render('Lotofootv2Bundle:User/CL:_chunk_result_cl.html.twig', $data);
    }
    
    /**
     * @Route("/cl/board/results_all", name="_cl_board_results_all")
     */
    public function resultsAllAction(Request $request)
    {
        
        $tour_s = $this->get('tournament_service');
        
        $tour_number = $request->query->get('tour_number');
        $tour_steps = $tour_s->getTourStepsByNumber($tour_number);
        
        if($tour_steps == null || count($tour_steps) == 0){
            return new Response("Aucune donnée");
        }
        
        $players = null;
        if(count($tour_steps) == 1){
            $players = $tour_s->getTourStepPlayers($tour_steps[0]->getId());
        }else{//on a passé les players sur l'id du step n°2 (step retour)
            $players = $tour_s->getTourStepPlayers($tour_steps[1]->getId());
        }

         $accs = $this->get('account_service')->all();
            
         foreach($accs as $a){
                //acc_accountid
             $request->request->set('acc_'.$a->getId(), $a->getUsername());
         }
        
        $data = array();
        
        $data['players'] = $players;
        
        for($i=0;$i<count($tour_steps);$i++){
            $ts = $tour_steps[$i];

            $matches = $tour_s->getTourStepMatches($ts->getId());
            
            if($ts->getState() == "A"){
                $data['matchesA'] = $matches;
            }else{
                $data['matchesR'] = $matches;
            }
            
            if($ts->getDeadline() < new DateTime()){
                
                for($p=0;$p<count($players);$p++){
                    $votes = $tour_s->getTourStepVotes($ts->getId(), $players[$p]->getAccountId());
                    
                    for($v=0;$v<count($votes);$v++){
                        $vote = $votes[$v];
                        $request->request->set($vote->getTourMatchId().'_result_'.$players[$p]->getAccountId(), $vote->getResult());
                        $request->request->set($vote->getTourMatchId().'_score_'.$players[$p]->getAccountId(), $vote->getScore());
                        $request->request->set($vote->getTourMatchId().'_fgmin_'.$players[$p]->getAccountId(), $vote->getFirstGoalMin());
                    }               
                }
            }
        }
          
        return $this->render('Lotofootv2Bundle:User/CL:_chunk_result_cl_all.html.twig', $data);
    }
}

Symfony/src/Lotofootv2/Bundle/Controller/User/CL/ComingController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\CL;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class ComingController extends Controller
{
	/**
     * @Route("/cl/coming", name="_cl_coming")
     */
    public function indexAction()
    {
       return $this->render('Lotofootv2Bundle:User/CL:coming.html.twig');
    }
}

Symfony/src/Lotofootv2/Bundle/Controller/User/CL/PrizesController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\CL;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class PrizesController extends Controller
{
	
	/**
     * @Route("/cl/prizes", name="_cl_prizes")
     */
    public function indexAction()
    {
       return $this->render('Lotofootv2Bundle:User\CL:prizes.html.twig');
    }

}

Symfony/src/Lotofootv2/Bundle/Controller/User/CL/RulesController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\CL;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class RulesController extends Controller
{
	
	/**
     * @Route("/cl/rules", name="_cl_rules")
     */
    public function indexAction()
    {
       return $this->render('Lotofootv2Bundle:User\CL:rules.html.twig');
    }

}

Symfony/src/Lotofootv2/Bundle/Controller/User/Cup/PrizesController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\Cup;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class PrizesController extends Controller
{
	
	/**
     * @Route("/cup/prizes", name="_cup_prizes")
     */
    public function indexAction()
    {
       return $this->render('Lotofootv2Bundle:User\Cup:prizes.html.twig');
    }

}

Symfony/src/Lotofootv2/Bundle/Controller/User/Cup/RankingController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\Cup;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class RankingController extends Controller
{
	/**
     * @Route("/cup/ranking", name="_cup_ranking")
     */
    public function indexAction()
    {
    	$accounts = $this->get('cup_service')->getRankingAccounts();

        $matchCorrected = count($this->get('cup_service')->getClosedMatchs());

        $groups = $this->get('account_service')->listGroups();
        
    	return $this->render('Lotofootv2Bundle:User\Cup:ranking.html.twig', array('accounts' => $accounts, 'matchCorrected' => $matchCorrected, 'groups' => $groups));
    }
}

Symfony/src/Lotofootv2/Bundle/Controller/User/Cup/RulesController.php
<?php

namespace Lotofootv2\Bundle\Controller\User\Cup;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class RulesController extends Controller
{
	
	/**
     * @Route("/cup/rules", name="_cup_rules")
     */
    
    public function indexAction()
    {
    	$rewards = $this->get('reward_service')->getRewardedAccounts();
    	$accounts = $this->get('account_service')->all();
    
    
    	return $this->render('Lotofootv2Bundle:User\Cup:rules.html.twig', array('rewards' => $rewards, 'users'=>$accounts));
    }

}

Symfony/src/Lotofootv2/Bundle/Resources/views/User/League/vote.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	{% if leagueDay is defined and leagueDay is not null %}
	<br/><br/>
	<div class="row">
		<div class="col-xs-1" style="padding:0">
			<a href="{{ path('_league_vote')~'?prev='~leagueDay.number}}" title="Paris précédents"><img src="{{ asset('bundles/lotofootv2/img/prev.png') }}"/></a>
		</div>
		<div class="col-sm-3 hidden-xs">
			<div class="ligne-body">&nbsp;</div>
		</div>
		<div class="col-sm-4 col-xs-10 title-body">
			Journée {{leagueDay.number}}
		</div>
		<div class="col-sm-3 hidden-xs">
			<div class="ligne-body">&nbsp;</div>
		</div>
		<div class="col-xs-1" style="padding:0">
			<a href="{{ path('_league_vote')~'?next='~leagueDay.number}}" title="Derniers paris"><img src="{{ asset('bundles/lotofootv2/img/next.png') }}"/></a>
		</div>

	</div>
	{% endif %}
{% endblock %}

{% block body %}

<style type="text/css">
    .resultVoted{
        background-color : gray !important;
    }
</style>
        


	<div class="row">
	{% if leagueDay is null %}
		Aucune journée créée !		
	{% else %}
		
		
			{% if leagueDay.word == "" %}
				{% if is_king == true %}
					<form action="{{ path('_league_vote_word') }}" method="post" class="form-punchline">
						
						<img src="{{ asset('bundles/lotofootv2/img/rewards/r1.png') }}"/> &nbsp;&nbsp;&nbsp;<strong>Bravo!</strong><br/> Vous êtes le meilleur joueur de la dernière journée, vous pouvez adresser une punchline qui sera affichée à tous les autres parieurs (max 150 caractères):<br/><br/>
						
						<div class="row" style="margin:0!important; text-align:center;">
							<textarea name="word" style="width:100%;height:50px;" maxlength="150">{{leagueDay.word}}</textarea>					
							<input type="submit" class="btn-admin" value="Publier"/>
						</div>

					</form>
				{% endif %}
			{% else %}
			
				{% if leagueDay.word is not null %}
					<div class="row">
						<fieldset class="form-punchline">
							<legend class="king-punchline-legend">&nbsp;La PunchLine du KING&nbsp;</legend>
							<blockquote style="padding:0 20px; margin:0; font-style:italic;" >&ldquo; {{leagueDay.word}} &rdquo;</blockquote><br/>
							<span class="king-punchline-sign">- {{leagueDay.kingTag}} -</span>
						</fieldset>
					</div>
				{% endif %}
		{% endif %}	
		<br/>
		<div class="row" style="text-align:center;">Date limite pour voter à cette journée : 
			<span style="font-weight: bold">
				{% if nextDeadline is defined and nextDeadline is not null %}
				     {{ nextDeadline|date("d/m/Y H:i") }}
				{% else %}
				     {{ leagueDay.deadline|date("d/m/Y H:i") }}
				{% endif %}
			&nbsp;&nbsp;&nbsp;</span>
			<input type="button" class="btn-admin tooltip-on" value="Auto 1 N 2" data-title="Remplit automatiquement le resultat en fonction du score !" onclick="autoResult()"/>
			
			{% if error is defined %}
		    <div style="color:red">{{ error }}</div>
			{% endif %}
			{% if info is defined and info is not null %}
		    <div style="color:green">{{ info }}</div>
			{% endif %}
			{% if warn is defined and warn is not null %}
		    <div style="color:orange">{{ warn }}</div>
			{% endif %}
		</div>
		<br/><br/>
		
		<div class="row">
			<form action="{{ path('_league_vote_post') }}" method="post">
	
				<table class="table-striped vote">
					<tr>
						<th>N°</th>
						<th>Domicile</th>
						<th>1</th>
						<th>N</th>
						<th>2</th>
						<th>Extérieur</th>
						<th>Score parié</th>
                        <th>Mon Bonus</th>
                        <th>Clôture</th>
					</tr>
					{% for match in matches %}
					<tr {{(match.bonus)?'class="bonus"':''}}>
						<td>
							{% if match.bonus == true %}
							<img src="{{ asset('bundles/lotofootv2/img/star.png') }}"/>
							{% endif %}
							{{match.number}}
							{% if match.bonus == true %}
							<img src="{{ asset('bundles/lotofootv2/img/star.png') }}"/>
							{% endif %}
						</td>
						<td>
							{{match.teamHome}}
						</td>
						<!-- deadline past -->
	                    {% if match.deadline > date() %}
	                    <td><input id="result_{{match.id}}_1" type="radio" name="result_{{match.id}}" value="1"
	                        {% if app.request.get('result_'~match.id) == '1' %}checked{% endif %}/> </td>
	                    <td><input id="result_{{match.id}}_N" type="radio" name="result_{{match.id}}" value="N"
	                        {% if app.request.get('result_'~match.id) == 'N' %}checked{% endif %}/> </td>
	                    <td><input id="result_{{match.id}}_2" type="radio" name="result_{{match.id}}" value="2"
	                        {% if app.request.get('result_'~match.id) == '2' %}checked{% endif %}/> </td>
	                    {% else %}
	                        <td {% if app.request.get('result_'~match.id) == '1' %} class="resultVoted" {%endif%}>&nbsp;</td>
	                        <td {% if app.request.get('result_'~match.id) == 'N' %} class="resultVoted" {%endif%}>&nbsp;</td>
	                        <td {% if app.request.get('result_'~match.id) == '2' %} class="resultVoted" {%endif%}>&nbsp;</td>
	                    {% endif %}
						<td>
							{{match.teamVisitor}}
						</td>
						<td>
						{% if match.deadline > date() %}
						      <input class="score_input" id="score_{{match.id}}" type="text" autocomplete="off" name="score_{{match.id}}" value="{{ app.request.get('score_'~match.id) }}" size="3" maxlength="3" style="width:50px;color:#333;text-align:center;" placeholder="x-x"/>
						{% else %}
							{{ app.request.get('score_'~match.id) }}
					     {% endif %}
						</td>
                        <td>
                            {% if match.deadline < date() and app.request.get('selfbonus') == match.id %}
                                <img src="{{ asset('bundles/lotofootv2/img/mstar.png') }}"/>
                            {% else %}
                                {# bonus selection is 'on' and match can be selected #}
                                {% if match.bonus == false and selfBonusLocked == false and match.deadline > date() %}
                                    <input name="selfbonus" type="radio" value="{{match.id}}" {% if app.request.get('selfbonus') == match.id %}checked{% endif %}/>
                                {% endif %}
                            {% endif %}
                        </td>
						<td>
                            {{match.deadline|date("d/m/Y H:i")}}
                        </td>
					</tr>
					{% endfor %}
				</table>

				<div class="row"  style="text-align:center;">
					<input type="submit" class="btn-admin" value="Valider vos votes pour la journée !" onclick="sub=true"/>
				</div>
				
			</form>
		</div>
	{% endif %}
	</div>	
	<script type="text/javascript">
	
	function autoResult(){
		if(confirm("Attention, cette action modifiera vos résultats selon le score parié")){
			$("[id^='score_']").each(function(){
				if($(this).val() != ""){
					var i = this.id.split("_")[1];
					var scores = $(this).val().split('-');
					if(scores[0] > scores[1]){
						$("#result_"+i+"_1").attr('checked', 'checked');
					}else if(scores[0] < scores[1]){
						$("#result_"+i+"_2").attr('checked', 'checked');
					}else if(scores[0] == scores[1]){
						$("#result_"+i+"_N").attr('checked', 'checked');
					}
				}
			});
		}
	}

    $('.score_input').on('blur', function(e){
		if(this.value.length == 2 && new RegExp('^\\d{2}$').test(this.value)){
			var spl = this.value.split("")
			this.value=spl[0]+'-'+spl[1]
		}
    });

	var sub = false;
    var changed = false;
	
    $("table.vote td input").on('change', function(){
        changed = true;
    });

    window.onbeforeunload = function(){
        console.log(changed, sub)
        if(changed && !sub){
            return "Attention, des modifications n'ont pas été enregistrées";
        }
    }; 
	
	</script>
	
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}