Symfony/src/Lotofootv2/Bundle/Entity/Account.php
<?php

namespace Lotofootv2\Bundle\Entity;

use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Account
 *
 * @ORM\Entity
 * @ORM\Table(name="lfv2_account")
 */
class Account implements AdvancedUserInterface, \Serializable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="team", type="string", length=16, nullable=true)
     */
    private $team;       
    
    /**
     * @ORM\Column(type="string", length=32)
     */
    private $salt;
    
    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;
    
    /**
     * @ORM\Column(name="is_admin", type="boolean")
     */
    private $isAdmin;
    
    /**
     * @ORM\Column(name="points", type="integer")
     */
    private $points;
    
    /**
     * @ORM\Column(name="rank", type="integer")
     */
    private $rank;
    
    /**
     * @ORM\Column(name="progression", type="integer")
     */
    private $progression;
    
    /**
     * @ORM\Column(name="stat_days", type="integer")
     */
    private $statDays;
    
    /**
     * @ORM\Column(name="stat_bonuses", type="integer")
     */
    private $statBonuses;

    /**
     * @ORM\Column(name="stat_results", type="integer")
     */
    private $statResults;
    
    /**
     * @ORM\Column(name="stat_scores", type="integer")
     */
    private $statScores;
    
     /**
     * @ORM\Column(name="cagnoute", type="boolean")
     */
    private $cagnoute;
    
        /**
     * @ORM\Column(name="cup_points", type="integer")
     */
    private $cupPoints;
    
    /**
     * @ORM\Column(name="cup_rank", type="integer")
     */
    private $cupRank;
    
    /**
     * @ORM\Column(name="stat_cup_matchs", type="integer")
     */
    private $statCupMatchs;
    
    /**
     * @ORM\Column(name="stat_cup_results", type="integer")
     */
    private $statCupResults;
    
    /**
     * @ORM\Column(name="stat_cup_scores", type="integer")
     */
    private $statCupScores;
    
     /**
     * @ORM\Column(name="cup_cagnoute", type="boolean")
     */
    private $cupCagnoute;
    
    /**
     * @ORM\Column(name="wins_league", type="integer")
     */
    private $winsLeague = 0;
    
    /**
     * @ORM\Column(name="wins_cup", type="integer")
     */
    private $winsCup = 0;
    
    /**
     * @ORM\Column(name="wins_cl", type="integer")
     */
    private $winsCL = 0;

    /**
     * @ORM\Column(name="groups", type="string", length=64, nullable=true)
     */
    private $groups;

    
    public function __construct()
    {
    	$this->isActive = false;
    	$this->isAdmin = false;
    	$this->points = 0;
    	$this->progression = 0;
    	$this->rank = 99;
    	$this->statBonuses = 0;
    	$this->statDays = 0;
    	$this->statResults = 0;
    	$this->statScores = 0;
    	$this->cagnoute = false;
    	$this->salt = '';
    	//cup
    	$this->cupCagnoute = false;
    	$this->cupPoints = 0;
    	$this->cupRank = 99;
    	$this->statCupMatchs = 0;
    	$this->statCupResults = 0;
    	$this->statCupScores = 0;
    	
    	$this->winsCL = 0;
    	$this->winsLeague = 0;
    	$this->winsCup = 0;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return Account
     */
    public function setUsername($username)
    {
        $this->username = $username;
    
        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return Account
     */
    public function setPassword($password)
    {
        $this->password = $password;
    
        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }
    
    public function setPoints($points)
    {
    	$this->points = $points;
    
    	return $this;
    }

    public function getPoints()
    {
    	return $this->points;
    }
    
	public function setRank($rank)
    {
    	$this->rank = $rank;
    
    	return $this;
    }

    public function getRank()
    {
    	return $this->rank;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Account
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

        /**
     * Set email
     *
     * @param string $email
     * @return Account
     */
    public function setTeam($team)
    {
        $this->team = $team;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getTeam()
    {
        return $this->team;
    }
    
    
    /**
     * Set progression
     *
     * @param string $progression
     * @return Account
     */
    public function setProgression($progression)
    {
        $this->progression = $progression;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getProgression()
    {
        return $this->progression;
    }
    
    public function getStatDays()
    {
    	return $this->statDays;
    }
    
    public function setStatDays($stat)
    {
    	$this->statDays = $stat;
    	
    	return $this;
    }
    
	public function getStatBonuses()
    {
    	return $this->statBonuses;
    }
    
	public function setStatBonuses($stat)
    {
    	$this->statBonuses = $stat;
    	
    	return $this;
    }
    
	public function getStatScores()
    {
    	return $this->statScores;
    }
    
	public function setStatScores($stat)
    {
    	$this->statScores = $stat;
    	
    	return $this;
    }
    
	public function getStatResults()
    {
    	return $this->statResults;
    }

	public function setStatResults($stat)
    {
    	$this->statResults = $stat;
    	
    	return $this;
    }
    
    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
    	return serialize(array(
    			$this->id,
    	));
    }
    
    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
    	list (
    			$this->id,
    	) = unserialize($serialized);
    }
    
    /**
     * @inheritDoc
     */
    public function getSalt()
    {
    	return $this->salt;
    }
    
    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }
    
    /**
     * @inheritDoc
     */
    public function getRoles()
    {
    	if($this->isAdmin){
    		return array('ROLE_ADMIN');
    	}else{
    		return array('ROLE_USER');
    	}
    }
    
	public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }
    
    public function isAdmin()
    {
        return $this->isAdmin;
    }
    
    public function setActive($active)
    {
    	$this->isActive = $active;
    }

	public function setCagnoute($cagnoute)
    {
    	$this->cagnoute = $cagnoute;
    
    	return $this;
    }

    public function getCagnoute()
    {
    	return $this->cagnoute;
    }
    
    public function setCupCagnoute($cupCagnoute)
    {
        $this->cupCagnoute = $cupCagnoute;
    
        return $this;
    }

    public function getCupCagnoute()
    {
        return $this->cupCagnoute;
    }
    
    public function setCupPoints($cupPoints)
    {
        $this->cupPoints = $cupPoints;
    
        return $this;
    }

    public function getCupPoints()
    {
        return $this->cupPoints;
    }
    
    public function setCupRank($rank)
    {
        $this->cupRank = $rank;
    
        return $this;
    }

    public function getCupRank()
    {
        return $this->cupRank;
    }
    
    public function getStatCupMatchs()
    {
        return $this->statCupMatchs;
    }
    
    public function setStatCupMatchs($statCup)
    {
        $this->statCupMatchs = $statCup;
        
        return $this;
    }
    
    public function getStatCupScores()
    {
        return $this->statCupScores;
    }
    
    public function setStatCupScores($statCup)
    {
        $this->statCupScores = $statCup;
        
        return $this;
    }
    
    public function getStatCupResults()
    {
        return $this->statCupResults;
    }

    public function setStatCupResults($statCup)
    {
        $this->statCupResults = $statCup;
        
        return $this;
    }
    
    public function getWinsCL()
    {
        return $this->winsCL;
    }
    public function getWinsLeague()
    {
        return $this->winsLeague;
    }
    public function getWinsCup()
    {
        return $this->winsCup;
    }

    public function getGroups()
    {
        return $this->groups;
    }

    public function setGroups($group)
    {
        $this->groups = $group;

        return $this;
    }
}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/admin.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
		<div class="container container-home" style="text-align:center;">

			<div class="title-body">
				ADMINISTRATION
			</div>

		</div>	
	</div>
{% endblock %}

{% block body %}
<div class="row">
		<div class="container container-home">
		<header class="menu-header">
				<nav class="menu-item-admin">
					{% if is_granted('ROLE_ADMIN') %}
					<a href="{{ path('_admin_users') }}" title="Administrer les utilisateurs">Admin utilisateurs</a>					
					<a href="{{ path('_admin_cup') }}" title="Administrer World Cup">Admin World Cup</a>
					<a href="{{ path('_admin_news') }}" title="Administrer les news">Poster une News</a>	
					{% endif %}
				</nav>

			</header>
	</div>
	</div>
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/cl.html.twig
{% set bg_cl = true %}

{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
			<div class="col-sm-6 col-xs-12 title-body">
				Admin Champion's League	&nbsp;
			<img src="{{ asset('bundles/lotofootv2/img/title-cl.png') }}"/>
			</div>
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
		</div>	
{% endblock %}

{% block body %}
	
	{% if err is defined and err is not null %}
		<div>ERREUR : ${err}</div>
	{% endif %}
	
	{% if step is null %}
		<b>Aucune ligue des champions trouvée !</b>
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_cl:create.html.twig' %}
		
	{% elseif step.state == "W" %}				
			
		{% include 'Lotofootv2Bundle:Admin/_chunks_cl:create_matchs.html.twig' %}	
		
	{% else %}
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_cl:running_step.html.twig' %}
		
	{% endif %}	
	
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/cup.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
		<div class="container container-home" style="text-align:center;">

			<div class="title-body">
				ADMINISTRATION COUPE DU MONDE
			</div>

		</div>	
	</div>
{% endblock %}

{% block body %}
<div class="row">
		<div class="container container-home">
	<div class="stop-float"></div>
	
	<a href="{{ path('_admin_cup_stats') }}" class="push_button blue">Statistiques et votes</a>
	
	<h3>Correction des matchs</h3>
	
	   <form class="form form-horizontal" action="{{ path('_admin_cup_correct') }}" method="post">
	       <table class="table table-striped">
            <tr>
                <th>
                    N°
                </th>
                <th>
                    Équipe A
                </th>
                <th>
                    Score 120'
                </th>
                <th>
                    Résultat Final
                </th>
                <th>
                    Équipe B
                </th>
            </tr>
	       {% for match in nc_matchs %}
	       <tr  class="vote-cup">
                <td>
                    {{match.id}}
                </td>
                <td>
                    <div class="drapeau {{match.teamHome}}"></div><div class="match-cup">{{('nationalteams.'~match.teamHome) | trans}}
                </td>
                {% if match.deadline|date('U') < "now"|date('U') %}
                <td>
                    <input type="text" name="score_{{match.id}}" size="3" autocomplete="off"  style="border:0px" value="{{app.request.get('score_'~match.id)}}"/>                                                           
                </td>
                <td>
                    <input type="text" name="result_{{match.id}}" size="3" autocomplete="off"  style="border:0px" value="{{app.request.get('result_'~match.id)}}"/>                                                           
                </td>
                {% else %}
                <td style="background-color:#65ad61; color:white">
                    Pari en cours<br/>
                    {{match.deadline|date('d/m/Y H:i')}}                                                
                </td>
                <td>
                </td>              
                {% endif %}
                <td>
                    <div class="drapeau {{match.teamVisitor}}"></div><div class="match-cup">{{('nationalteams.'~match.teamVisitor) | trans}}
                </td>
            </tr>
            
	       
	       {% endfor %}
	       </table>
	       
	       <input type="submit" name="Valider" class="push_button blue"/>  
	       
	   </form>
	
	
	<br/>
	<h3>Nouveaux matchs</h3>
	<br/>
	
	<form action="{{ path('_admin_cup_matchs_create') }}" method="post" style="width:800px;margin:auto">
	
	    <table class="table table-striped" id="match-table">
	        <tr>
	            <th>
	                N°
	            </th>
	            <th>
	                Équipe A
	            </th>
	            <th>
	                Équipe B
	            </th>
	            <th>
	                 Facteur
	            </th>
	            <th>
                     Deadline J
                </th>
                <th>
                     Deadline H
                </th>
	        </tr>
	        {% for i in 1..8 %}
	        <tr class="vote-cup">
	            <td>
	                {{i}}
	            </td>
	            <td>
	                <input type="text" name="home_{{i}}" value="{{ app.request.get('home_'~i) }}" style="border:0px"/>
	            </td>
	            <td>
	                <input type="text" name="visitor_{{i}}" value="{{ app.request.get('visitor_'~i) }}" style="border:0px"/>
	            </td>
	            <td>
	                <input type="text" name="factor_{{i}}" value="{{ app.request.get('factor_'~i) }}" style="border:0px; width:50px;"/>
	            </td>
	            <td>
                    <input type="text" name="deadline_{{i}}" value="{{ app.request.get('deadline_'~i) }}" placeholder="jj/mm/aaaa" style="border:0px; width:70px;"/>
                </td>
                <td>
                    <input type="text" name="deadlineh_{{i}}" value="{{ app.request.get('deadlineh_'~i) }}" placeholder="HH:mm" style="border:0px; width:50px;"/>
                </td>
	        </tr>
	        {% endfor %}
	    </table>
	    
	    <input type="submit" class="push_button blue" value="Lancer !"/>
    
    </form>
    

    
<h3>Abbréviations des équipes nationales</h3>	
<ul>
	<li>ALL:Allemagne</li>
	<li>ANG:Angleterre</li>
	<li>ARS:Arabie Saoudite</li>
	<li>ARG:Argentine</li>
	<li>AUS:Australie</li>
	<li>BEL:Belgique</li>
	<li>BRE:Brésil</li>
	<li>COL:Colombie</li>
	<li>CDS:Corée du Sud</li>
	<li>CRI:Costa Rica</li>
	<li>CRO:Croatie</li>
	<li>DAN:Danemark</li>
	<li>EGY:Egypte</li>
	<li>ESP:Espagne</li>
	<li>FRA:France</li>
	<li>IRN:Iran</li>
	<li>ISL:Islande</li>
	<li>JAP:Japon</li>
	<li>MAR:Maroc</li>
	<li>MEX:Mexique</li>
	<li>NGA:Nigeria</li>
	<li>PAN:Panama</li>
	<li>PER:Pérou</li>
	<li>POL:Pologne</li>
	<li>POR:Portugal</li>
	<li>RUS:Russie</li>
	<li>SEN:Sénégal</li>
	<li>SER:Serbie</li>
	<li>SUE:Suède</li>
	<li>SUI:Suisse</li>
	<li>TUN:Tunisie</li>
	<li>URU:Uruguay</li>


</ul>
</div>
</div>
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/cup_stats.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
		<div class="container container-home" style="text-align:center;">

			<div class="title-body">
				STATS COUPE DU MONDE
			</div>

		</div>	
	</div>
{% endblock %}

{% block body %}
<div class="row">
		<div class="container container-home">
	<div class="stop-float"></div>
	
    <br/>
    <h3>Matchs terminés</h3>
    <br/>
     {% if stats is not null %}
      <table class="table table-striped" id="match-table">
          <tr>
              <th>
                  N°
              </th>
              <th>
                  Match
              </th>
              <th>
                   Deadline
              </th>
              <th>
                   Nb Votants
              </th>
              <th>
                   Moyenne
              </th>
              <th>
                   Nb Resultats
              </th>
              <th>
                   Nb Scores
              </th>
          </tr>
          {% for s in stats %}
          <tr class="vote-cup">
              <td>
                  {{s.id}}
              </td>
              <td>
              	<div class="drapeau {{s.team_home}}"></div><div class="match-cup">{{('nationalteams.'~s.team_home) | trans}} </div>                 
              	<div class="match-cup">{{('nationalteams.'~s.team_visitor) | trans}} </div> <div class="drapeau {{s.team_visitor}}" style="margin-left:5px;"></div>
              </td>
              <td>
                  {{s.deadline|date('d/m/Y H:i')}}
              </td>
              <td>
                  {{s.votants}}
              </td>
              <td>
                  {{s.moyenne|number_format(2, '.', ',')}}
              </td>
              <td>
                  {{s.nbresult}}
              </td>
              <td>
                  {{s.nbscore}}
              </td>
          </tr>
          {% endfor %}
      </table>
      {% endif %}
      
    <br/>
      {% if next is not null %}<h3>Prochain match le {{next.deadline|date('d/m/Y H:i')}}</h3>
    <div class="drapeau {{next.teamHome}}"></div> <h4>{{('nationalteams.'~next.teamHome)|trans}} </h4>
    <div class="drapeau {{next.teamVisitor}}"></div> <h4>{{('nationalteams.'~next.teamVisitor)|trans}} </h4>{% endif %}
    <br/>
    <u><b>N'a pas voté ({{not_voted|length}}):</b></u> <br/>
    {% for v in not_voted %}
        {{v.username}}, 
    {% endfor %}
    <br/><br/>
    {% for v in not_voted %}
        {{v.email}}; 
    {% endfor %}
    
    <br/><br/>
        <u><b>A voté ({{voted|length}}):</b></u> <br/>
    {% for v in voted %}
        {{v.username}}, 
    {% endfor %}
    <br/><br/>
    {% for v in voted %}
        {{v.email}};
    {% endfor %}
    </div></div>  
      
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/day.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block body %}
	Admin de la journée
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/league.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
			<div class="col-sm-6 col-xs-12 title-body">
				Admin Saison Championnat			&nbsp;
			<img src="{{ asset('bundles/lotofootv2/img/picto-winner-league.png') }}"/>
			</div>
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
		</div>	
{% endblock %}

{% block body %}
	<div class="stop-float"></div>
	
	{% if league is null %}
		<b>Aucune saison trouvée !</b>
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_league:create.html.twig' %}
		
		{% else %}
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_league:display.html.twig' %}
		
	{% endif %}	
	
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/league_day.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<br/><br/>
	<div class="row">
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
			<div class="col-sm-6 col-xs-12 title-body">
				Admin Journée Championnat			&nbsp;
			<img src="{{ asset('bundles/lotofootv2/img/picto-winner-league.png') }}"/>
			</div>
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
		</div>	
{% endblock %}

{% block body %}
	<div class="row" style="text-align:center;">

	{% if leagueDay is not defined or leagueDay is null %}
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_league_day:new.html.twig' %}
		
	{% else %}
		
		{% include 'Lotofootv2Bundle:Admin/_chunks_league_day:mark.html.twig' %}
	
	{% endif %}
	</div>
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/new_cup.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
			<div class="col-sm-6 col-xs-12 title-body">
				Création d'une Cup
			</div>
			<div class="col-sm-3 hidden-xs">
				<div class="ligne-body">&nbsp;</div>
			</div>
		</div>	
{% endblock %}

{% block body %}
	<div class="stop-float"></div>
	
	<form class="form form-horizontal" action="{{ path('_admin_cup_create') }}" method="post">
    
	    <div class="control-group">
	        <label class="control-label" for="_name">
	             Nom de la cup <span style="color:red"> * </span> 
	        </label>
	        <div class="controls">
	             <input type="text" id="_name" name="name" value=""/>
	        </div>
	    </div>
	    
	    <div class="control-group">
	        <div class="controls">
	             <input type="submit" value="Créer"/>
	        </div>
	    </div>
	</form>
	
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}

Symfony/src/Lotofootv2/Bundle/Resources/views/Admin/users.html.twig
{% extends 'Lotofootv2Bundle::layout.html.twig' %}

{% block navibar %}
	{% include 'Lotofootv2Bundle::navibar.html.twig' %}
{% endblock %}

{% block menu %}
	{% include 'Lotofootv2Bundle::menu.html.twig' %}
{% endblock %}

{% block title_body %}
	<div class="row">
		<div class="container container-home" style="text-align:center;">

			<div class="title-body">
				ADMINISTRATION DES UTILISATEURS
			</div>

		</div>	
	</div>
{% endblock %}

{% block body %}
<div class="row">
		<div class="container container-home">
	<table  class="table-striped vote">
		<tr>
			<th>ID</th>
			<th>Utilisateur</th>
			<th>Email</th>
			<th>Activation</th>
			<th>Adminitrateur</th>
			<th>cagnoute</th>
		</tr>
		{% for u in users %}
		<tr>
			<td>
				{{u.ID}}
			</td>
			<td>
				{{u.username}} &nbsp; {% if u.cupCagnoute %}
					<img src="{{ asset('bundles/lotofootv2/img/rewards/r9.png') }}" style="width:16px;height:16px"/>{% endif %}	
			</td>
			<td>
				{{u.email}}
			</td>
			<td>
				<a href="{{ path('_admin_users_activation') }}?id={{u.id}}">
					{% if u.enabled %}
					<span style="color:green">Passer inactif</span>
					{% else %}
					<span style="color:red">Passer actif</span>
					{% endif %}				
				</a>
			</td>
			<td>
				{% if u.admin %}
					<img src="{{ asset('bundles/lotofootv2/img/found.png') }}" style="width:16px;height:16px"/>
				{% endif %}				
			</td>
			<td>
				<a href="{{ path('_admin_cagnoute_activation') }}?id={{u.id}}">
					{% if u.cupCagnoute %}
					<span style="color:green">Enlever Cagnoute</span>
					{% else %}
					<span style="color:red">Ajouter Cagnoute</span>
					{% endif %}				
				</a>
		
			</td>
		</tr>
		{% endfor %}
	</table>
</div>
</div>
	
{% endblock %}

{% block footer %}
	{% include 'Lotofootv2Bundle::footer.html.twig' %}
{% endblock %}